### ISSUE TITLE
change of hostname does not take effect

### ISSUE THREAD

**Issue by MRChriz385** [bitwarden/self-host#108]
hello guys, 
 

I use VM with Ubuntu desktop on a Synology NAS. 

I already installed Bitwarden with docker and can access the installation with https://localhost. 

When I change the hostname in the global.override.conf for example in: https://bitwarden.local or bitwarden-xy.xy it does not work.  Using an IP Address does not work either. 

I checked the nginx config, and the hostname I choose is found there. But I still cannot access bitwarden with another name as localhost. 

Does anyone have a solution for that?

**Comment by MRChriz385** [comment]
Hi @atjbramley, 

thank you for your fast answer. 

I changed the hostname and started ./bitwarden.sh rebuild. Then I got this error: 

`
bitwarden.sh version 2023.4.3
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
docker-compose version 1.29.2, build unknown

Stopping bitwarden-nginx         ... done
Stopping bitwarden-admin         ... done
Stopping bitwarden-notifications ... done
Stopping bitwarden-icons         ... done
Stopping bitwarden-web           ... done
Stopping bitwarden-api           ... done
Stopping bitwarden-sso           ... done
Stopping bitwarden-mssql         ... done
Stopping bitwarden-events        ... done
Stopping bitwarden-attachments   ... done
Stopping bitwarden-identity      ... done
Removing bitwarden-nginx         ... done
Removing bitwarden-admin         ... done
Removing bitwarden-notifications ... done
Removing bitwarden-icons         ... done
Removing bitwarden-web           ... done
Removing bitwarden-api           ... done
Removing bitwarden-sso           ... done
Removing bitwarden-mssql         ... done
Removing bitwarden-events        ... done
Removing bitwarden-attachments   ... done
Removing bitwarden-identity      ... done
Removing network docker_default
Removing network docker_public



Unhandled exception. YamlDotNet.Core.YamlException: (Line: 6, Col: 1, Idx: 193) - (Line: 6, Col: 29, Idx: 221): Exception during deserialization
 ---> System.InvalidCastException: Invalid cast from 'System.String' to 'Bit.Setup.Configuration'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(Object value, Type destinationType, CultureInfo culture)
   at YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(Object value, Type destinationType)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Bit.Setup.Context.LoadConfiguration() in /home/runner/work/server/server/util/Setup/Context.cs:line 153
   at Bit.Setup.Program.RebuildConfigs() in /home/runner/work/server/server/util/Setup/Program.cs:line 264
   at Bit.Setup.Program.Update() in /home/runner/work/server/server/util/Setup/Program.cs:line 161
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 55
`


The hostname in config.yml and global.override.conf is the same.

**Comment by atjbramley** [comment]
Hi @MRChriz385, 

At this stage we would like to use this GitHub page for commentary directly related to the issue itself.  Your next steps are likely to be configuration related, and as such I'd invite you to contact us through our contact form for Technical Assistance:

https://bitwarden.com/contact/

Please quote this issue to continue the discussion.

**Comment by MRChriz385** [comment]
hi @atjbramley, 

i solved these errors, but i still can not access the bitwarden app with the browser. The hostname in both config files is the same (bitwarden.local). i don't get any access now. 

Do you have an idea what I can do ?

**Comment by atjbramley** [comment]
@MRChriz385,

I'd invite you to contact us for support at https://bitwarden.com/contact/

We use GitHub issues as a place to track bugs and other development related issues.  I am afraid that we do not offer technical support via GitHub discussions, and would invite you to open a ticket with our support team if you require technical support.

**Comment by MRChriz385** [comment]
Hello @atjbramley 

i got your point. I am in contact with the bitwarden support. Thanks for your help!

**Comment by atjbramley** [comment]
Hi @MRChriz385,

Thank you for contacting support - we'll be happy to look at your configuration issues there.

We'd like to leave the GitHub issue open, as you identified a bug that our development team would like to investigate.  Our team will use this issue to GitHub page for commentary directly related to the issue itself.
