### ISSUE TITLE
Broken feature after update 2023.5.0 - Unable to add user access permissions on Organization Collections

### ISSUE THREAD

**Issue by giuliolibrando** [bitwarden/self-host#186]
I'm unable to add user to a Collection in my Organization after the docker image upgrade. If i add a Group instead it works. The procedure gives a green pop up but the user is not added to the Collection access rules.
![image](https://github.com/bitwarden/self-host/assets/76574961/c76fea98-8caf-4823-95b7-d9cd399b814d)
![image](https://github.com/bitwarden/self-host/assets/76574961/6f1232dd-2e70-45c7-b487-c80762ea324d)
Tried with every user role (Owner, Administrator etc etc).

The feature worked until bitwarden 2023.5.0, i'm unable to downgrade to any older version because there's no beta tag that can go further past. I'm stuck with the latest bitwarden/self-host:beta now 

I have no error in the browser console or the kubernetes container
![image](https://github.com/bitwarden/self-host/assets/76574961/38605af4-964b-4a9b-bbf1-6c3b3aae8ab7)
![image](https://github.com/bitwarden/self-host/assets/76574961/da867c05-9bd0-4e91-bf65-51f46a262ecc)

**Comment by giuliolibrando** [comment]
I felt hopeful after reading the changelog of the 2023.12.0 release "Bug fix for users with custom permissions import to organization".
I updated the container to the latest beta (2023.12.0) but the bug persists

**Comment by rsulzenbacher** [comment]
Same here... 
When trying to update permissions on organisations. 
in the UI: `An unhandled server error has occurred.`

in api.log:
```
2024-01-03 10:25:21.969 +00:00 [ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Bit.Infrastructure.EntityFramework.Repositories.DatabaseContextExtensions.UserBumpAccountRevisionDateAsync(DatabaseContext context, Guid userId) in /source/src/Infrastructure.EntityFramework/Repositories/DatabaseContextExtensions.cs:line 13
   at Bit.Infrastructure.EntityFramework.Repositories.OrganizationUserRepository.ReplaceAsync(OrganizationUser organizationUser) in /source/src/Infrastructure.EntityFramework/Repositories/OrganizationUserRepository.cs:line 425
   at Bit.Infrastructure.EntityFramework.Repositories.OrganizationUserRepository.ReplaceAsync(OrganizationUser obj, IEnumerable`1 requestedCollections) in /source/src/Infrastructure.EntityFramework/Repositories/OrganizationUserRepository.cs:line 432
   at Bit.Core.Services.OrganizationService.SaveUserAsync(OrganizationUser user, Nullable`1 savingUserId, IEnumerable`1 collections, IEnumerable`1 groups) in /source/src/Core/Services/Implementations/OrganizationService.cs:line 1328
   at Bit.Api.AdminConsole.Controllers.OrganizationUsersController.Put(String orgId, String id, OrganizationUserUpdateRequestModel model) in /source/src/Api/AdminConsole/Controllers/OrganizationUsersController.cs:line 300
   at lambda_method35(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

I'm using Version 2023.12.0.
Docker on Ubuntu Linux with MariaDB as database.

**Comment by rsulzenbacher** [comment]
I found the cause of my issue. 
The user account I wanted to edit the permissions wasn't fully confirmed in my organisation. 
After confirmation I can edit the permissions without any problems.

**Comment by wardragon** [comment]
still there, any news?
