### ISSUE TITLE
Error when updating to 2024.1.0

### ISSUE THREAD

**Issue by ilkevinli** [bitwarden/self-host#192]
Hi. After updating the script to the latest version and then running the update command, I am receiving the following error, 

 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2024, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2024.1.0
Docker version 24.0.7, build afdd53b
Docker Compose version v2.20.3

[+] Running 13/13
 ✔ Container bitwarden-icons          Removed                                                                                                      1.4s
 ✔ Container bitwarden-notifications  Removed                                                                                                      1.4s
 ✔ Container bitwarden-sso            Removed                                                                                                      1.3s
 ✔ Container bitwarden-events         Removed                                                                                                      1.1s
 ✔ Container bitwarden-attachments    Removed                                                                                                      1.0s
 ✔ Container bitwarden-nginx          Removed                                                                                                      1.5s
 ✔ Container bitwarden-web            Removed                                                                                                      0.6s
 ✔ Container bitwarden-api            Removed                                                                                                      1.0s
 ✔ Container bitwarden-identity       Removed                                                                                                      0.9s
 ✔ Container bitwarden-admin          Removed                                                                                                      0.9s
 ✔ Container bitwarden-mssql          Removed                                                                                                      0.8s
 ✔ Network docker_public              Removed                                                                                                      0.2s
 ✔ Network docker_default             Removed                                                                                                      0.3s
2024.1.0: Pulling from bitwarden/setup
b5a0d5c14ba9: Pull complete
633d76141204: Pull complete
1848b362d065: Pull complete
fbe27472c7a1: Pull complete
f1dad1ba8f85: Pull complete
5086debf0418: Pull complete
e092098130a8: Pull complete
0d0f68a904a8: Pull complete
b60aca579b54: Pull complete
ce406edb9606: Pull complete
Digest: sha256:*****
Status: Downloaded newer image for bitwarden/setup:2024.1.0
docker.io/bitwarden/setup:2024.1.0

Unhandled exception. YamlDotNet.Core.YamlException: (Line: 90, Col: 11, Idx: 3822) - (Line: 90, Col: 25, Idx: 3836): Exception during deserialization
 ---> System.InvalidCastException: Invalid cast from 'System.String' to 'System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(Object value, Type destinationType, CultureInfo culture)
   at YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(Object value, Type destinationType)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Bit.Setup.Context.LoadConfiguration() in /home/runner/work/server/server/util/Setup/Context.cs:line 154
   at Bit.Setup.Program.RebuildConfigs() in /home/runner/work/server/server/util/Setup/Program.cs:line 312
   at Bit.Setup.Program.Update() in /home/runner/work/server/server/util/Setup/Program.cs:line 162
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 56
root@bitwarden:/home/kc#

I have never had an issue updating before. This is on a ubuntu VM. I was able to restore a snapshot and everything is back fine with the previous version. I did try the update again and received the same error. Any suggestions ? Thanks

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration on line 90 of your YAML file.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by ilkevinli** [comment]
Hi Sam,
             Thank you for replying. The issue was I has the "real_ips" option enabled. I'm not sure why having that enabled would cause the issue though. Once I commented that option out, the update worked.
