### ISSUE TITLE
bitwarden.sh update - 2024.2.2 - Value cannot be null

### ISSUE THREAD

**Issue by git-tec** [bitwarden/self-host#217]
After starting the bitwarden.sh update for 2024.2.2 it ends with

Total reclaimed space: 2.449GB
Pausing 60 seconds for database to come online. Please wait...
2024.2.2: Pulling from bitwarden/setup
Digest: sha256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Status: Image is up to date for bitwarden/setup:2024.2.2
docker.io/bitwarden/setup:2024.2.2

Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'logger')
   at System.ThrowHelper.Throw(String paramName)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogInformation(ILogger logger, String message, Object[] args)
   at Bit.Migrator.DbMigrator.MigrateMsSqlDatabaseWithRetries(Boolean enableLogging, Boolean repeatable, String folderName, CancellationToken cancellationToken) in /home/runner/work/server/server/util/Migrator/DbMigrator.cs:line 46
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/runner/work/server/server/util/Setup/Program.cs:line 194
   at Bit.Setup.Program.Update() in /home/runner/work/server/server/util/Setup/Program.cs:line 158
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 56
   
anyone with the same error? However, Bitwarden seems to be running in version 2024.2.2

**Comment by vinnyperella** [comment]
I received the same error after upgrading to 2024.2.1. I was also having issues with my nginx container starting that seems to be intermittent.

**Comment by DimebagCFH** [comment]
Experiencing the same issue @git-tec

**Comment by jtodddd** [comment]
Hi there,

This has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by nickjossy** [comment]
Just noticed the same error.  When I login to the admin portal it says I'm on an old version of both the server and the web:
![image](https://github.com/bitwarden/self-host/assets/50054095/4be3ab0c-c875-4b45-af88-887abfaaa1e6)
If I try the update process again it says "Update not needed".

Problem is that my organisation licence has expired, but I can't apply the new licence as it says "Version 14 is not supported"

**Comment by nickjossy** [comment]
Ok - ignore my earlier post about the version being old.  I have two instances and was looking at the wrong one. Doh!

However, after updating the in-use instance and then attempting to disable the old instance in Docker I came across what might be the source of the "Value cannot be Null" error.  If you look at the docker settings for the bitwarden-admin container the globalSettings__syslog__destination field appears to be empty and it requires a value.  This is preventing me making changes to the container - e.g. to make sure it stays shutdown!

![image](https://github.com/bitwarden/self-host/assets/50054095/562a8735-eebd-40dd-a34f-ecdd52f30cc7)

Hope this helps!

**Comment by sincerelysaucy** [comment]
Check your diskspace? The upgrade command can leave a lot of debris, especially if an update failed. And "/var/lib/docker/" can wind up overwhelmed by other content in the "/var/" partition, especially "/var/log/" if you've not left enough space in the relevant partition. auditd, in particular, tends to spew logs with docker running.

**Comment by vinnyperella** [comment]
This error was unrelated to disk space I have plent of space available on my VPS. I've upgraded a few times since encountering this error and have not seen it since.

**Comment by vinnyperella** [comment]
I received the error again after updating to 2024.03.0.

```
Total reclaimed space: 2.713GB
Pausing 60 seconds for database to come online. Please wait...
2024.3.0: Pulling from bitwarden/setup
Digest: sha256:e562d637dbff73b19fdbbd429a2322e405f4dd530273140b9693eea9d673587e
Status: Image is up to date for bitwarden/setup:2024.3.0
docker.io/bitwarden/setup:2024.3.0
WARN[0000] /opt/bitwarden/bwdata/docker/docker-compose.yml: `version` is obsolete 

Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'logger')
   at System.ThrowHelper.Throw(String paramName)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogInformation(ILogger logger, String message, Object[] args)
   at Bit.Migrator.DbMigrator.MigrateMsSqlDatabaseWithRetries(Boolean enableLogging, Boolean repeatable, String folderName, CancellationToken cancellationToken) in /home/runner/work/server/server/util/Migrator/DbMigrator.cs:line 46
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/runner/work/server/server/util/Setup/Program.cs:line 194
   at Bit.Setup.Program.Update() in /home/runner/work/server/server/util/Setup/Program.cs:line 158
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 56
```
However, just like last time the mssql container started successfully.
