### ISSUE TITLE
Issue with updating self-hosted bitwarden instance

### ISSUE THREAD

**Issue by apblack96** [bitwarden/self-host#46]
It looks like there is an issue with updating self-hosted bitwarden instances. After some troubleshooting it looks like the source of the issue is the run script url in the bitwarden script. See below:

RUN_SCRIPT_URL="https://func.bitwarden.com/api/dl/?app=self-host&platform=linux&variant=run"

This URL as of 2022-08-22T17:18:55Z UTC returns the following data:
StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: GET self-host/run.sh; It was not possible to connect to the redis server(s). ConnectTimeout, mc: 1/1/0, mgr: 10 of 10 available, clientName: appfunctions-9dcc4d77c-l2ksx, IOCP: (Busy=0,Free=1000,Min=24,Max=1000), WORKER: (Busy=2,Free=32765,Min=24,Max=32767), v: 2.1.58.34321
 ---> StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). ConnectTimeout
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2769
--- End of stack trace from previous location ---
   at Proxies.Downloads.GetDownloadUrlAsync(ValueTuple`4 valueTuple) in /home/runner/work/misc/misc/AzureFunctions/prod/AppFunctions/Downloads.cs:line 192
   at Proxies.Downloads.Run(HttpRequest req, ILogger log) in /home/runner/work/misc/misc/AzureFunctions/prod/AppFunctions/Downloads.cs:line 174

It looks like it is probably an issue for both linux and windows users.

**Comment by mimartin12** [comment]
Hey @apblack96, 

Can you try this again?

**Comment by joseph-flinn** [comment]
Thanks for reporting this! This issue has been resolved
